# Site settings
title: Typescene
description: >- # this means to ignore newlines until "baseurl:"
  Typescene is a strongly typed front end framework written in TypeScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://typescene.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: typescene
github_username: typescene

# Build settings
exclude:
  - docgen
  - docwidget
markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  syntax_highlighter: rouge